# permissions for end users to edit pitmasters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pitmaster-editor-role
rules:
- apiGroups:
  - racing.b4mad.net
  resources:
  - pitmasters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - racing.b4mad.net
  resources:
  - pitmasters/status
  verbs:
  - get
